name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yaml
          activate-environment: larest

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Install package
        run: uv pip install --system ".[tests]"

      - name: Run tests
        run: pytest tests/ --integration
